---
- hosts: localhost
  connection: local
  gather_facts: false

  # run:
  # $ export DO_API_TOKEN=your-token
  # then run this playbook to create droplet
  tasks:
    - digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: sfo2 # slug of the region you would like your server to be created in.   https://www.digitalocean.com/docs/platform/availability-matrix/
        image: wordpress-18-04 # slug of the image you would like the droplet created with.
        wait: yes
        name: "test-website" # name of the droplet
        size_id: s-1vcpu-2gb   # See https://slugs.do-api.dev/ for options
        state: present
        #ssh_keys: [ '0123456789' ] # <----- put your numeric SSH key in here
      register: created_droplet

    - digital_ocean_tag:
        name: some-sample-tag 
        resource_id: "{{ created_droplet.data.droplet.id }}"
        state: present
      register: tag_response

    - name: add hosts
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "do"
